version: "3.3"

services:
  cafeDB:
    image: postgres:12.1-alpine
    container_name: countries
    restart: unless-stopped
    ports:
      - 5429:5432
    environment:
      POSTGRES_USER: appUser
      POSTGRES_PASSWORD: 13
      POSTGRES_DB: cafeDB
      PGDATA: /var/lib/postgresql/pgdata
      TZ: "Europe/Moscow"
